#!/bin/bash
RETVAL=0

yang_list() {
 local RETVAL=0
 local HTTP_CODE=""
 local HTTP_RESPONSE=""
 local HTTP_PATH="${ODL_PREFIX}/data/ietf-yang-library:modules-state"
 local HTTP_BODY="/dev/null"
 local HTTP_METHOD="GET"
 local HTTP_CONTENT_TYPE="application/yang-data+json"
 local HTTP_ACCEPT="application/yang-data+json"
 mk_tmp_file HTTP_RESPONSE
 http_curl "${HTTP_RESPONSE}" "${HTTP_METHOD}" "${HTTP_PATH}" "${HTTP_BODY}" "${HTTP_CONTENT_TYPE}" "${HTTP_ACCEPT}"
 if [ ${CURL_RETVAL} -eq 0 ] ; then
   if [ "${CURL_HTTP_CODE:0:1}" == "2" ] ; then
      if [ -f "${HTTP_RESPONSE}" ] ; then
        local MODULES=$(jq -r ".\"ietf-yang-library:modules-state\".module | length" ${HTTP_RESPONSE})
        if [ ${MODULES} -gt 0 ] ; then
          local MODULE=0
#          echo "[]module-name|revision|namespace|conformance-type|schema|features"
          echo "[]module-name|revision|namespace|features"
          while [ ${MODULE} -lt ${MODULES} ] ; do
           local MODULE_NAME=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].name" ${HTTP_RESPONSE})
           local REVISION=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].revision" ${HTTP_RESPONSE})
           local NAMESPACE=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].namespace" ${HTTP_RESPONSE})
#           local CONFORMANCE_TYPE=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].\"conformance-type\"" ${HTTP_RESPONSE})
#           local SCHEMA=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].schema" ${HTTP_RESPONSE})
           local FEATURES=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].feature | length" ${HTTP_RESPONSE})
           local FEATURES_SET=""
           if [ ${FEATURES} -gt 0 ] ; then
             local FEATURE=0
             local FEATURE_IDX=0
             while [ ${FEATURE} -lt ${FEATURES} ] ; do
               local FEATURE_NAME=$(jq -r ".\"ietf-yang-library:modules-state\".module[${MODULE}].feature[${FEATURE}]" ${HTTP_RESPONSE})
               ((FEATURE_IDX=FEATURE+1))
               [[ ${FEATURE_IDX} -lt ${FEATURES} ]] && FEATURES_SET+="${FEATURE_NAME}," || FEATURES_SET+="${FEATURE_NAME}"
               ((FEATURE=FEATURE+1))
             done
           fi
#           echo "${MODULE_NAME,,}|${REVISION,,}|${NAMESPACE,,}|${CONFORMANCE_TYPE,,}|${SCHEMA,,}|${FEATURES_SET}"
           echo "${MODULE_NAME,,}|${REVISION,,}|${NAMESPACE,,}|${FEATURES_SET}"
           ((MODULE=MODULE+1))
          done
        fi
      fi
   else
    RETVAL=${CURL_RETVAL}
   fi
 else
   RETVAL=${CURL_RETVAL}
 fi
 rm_tmp_file "${HTTP_RESPONSE}"
 return ${RETVAL}
}


node_schemas_list() {
local RETVAL=0
 if [ $# -eq 0 ] ; then
  RETVAL=1
  return ${RETVAL}
 fi
 local HTTP_CODE=""
 local HTTP_RESPONSE="/dev/null"
 local NODE_ID="${1}"
 local HTTP_PATH="${ODL_PREFIX}/operations/network-topology:network-topology/topology=topology-netconf/node=${NODE_ID}/yang-ext:mount/ietf-netconf:get"
 local HTTP_BODY=""
 local HTTP_METHOD="POST"
 local HTTP_CONTENT_TYPE="application/xml"
 local HTTP_ACCEPT="application/yang-data+json"
 mk_tmp_file HTTP_RESPONSE
 mk_tmp_file HTTP_BODY
 cat >${HTTP_BODY} <<SCHEMAS-EOF
<input xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <filter type="subtree">
        <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
            <schemas/>
        </netconf-state>
    </filter>
</input>
SCHEMAS-EOF
 http_curl "${HTTP_RESPONSE}" "${HTTP_METHOD}" "${HTTP_PATH}" "${HTTP_BODY}" "${HTTP_CONTENT_TYPE}" "${HTTP_ACCEPT}"
 if [ ${CURL_RETVAL} -eq 0 ] ; then
   if [ "${CURL_HTTP_CODE:0:1}" == "2" ] ; then
     local SCHEMAS=0
     SCHEMAS=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema | length" ${HTTP_RESPONSE})
     if [ ${SCHEMAS} -gt 0 ] ; then
       local SCHEMA=0
       echo "[]identifier|version|format|namespace|location"
       while [ ${SCHEMA} -lt ${SCHEMAS} ] ; do
         local IDENTIFIER=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].identifier" ${HTTP_RESPONSE})
         local VERSION=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].version" ${HTTP_RESPONSE})
         local FORMAT=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].format" ${HTTP_RESPONSE})
         local NAMESPACE=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].namespace" ${HTTP_RESPONSE})
         local LOCATION=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].location" ${HTTP_RESPONSE})
         echo "${IDENTIFIER}|${VERSION,,}|${FORMAT,,}|${NAMESPACE,,}|${LOCATION}"
         ((SCHEMA=SCHEMA+1))
       done
     fi
      RETVAL=0
   else
      RETVAL=${CURL_HTTP_CODE}
   fi
 fi
 rm_tmp_file "${HTTP_BODY}"
 rm_tmp_file "${HTTP_RESPONSE}"
 return ${RETVAL}
}

node_schema_fetch() {
 if [ $# -eq 0 ] ; then
  RETVAL=1
  return ${RETVAL}
 fi
 local HTTP_CODE=""
 local HTTP_RESPONSE="/dev/null"
 local NODE_ID="${1,,}"
 local IDENTIFIER="${2,,}"
 local REVISION="${3,,}"
 local HTTP_PATH="${ODL_PREFIX}/operations/network-topology:network-topology/topology=topology-netconf/node=${NODE_ID}/yang-ext:mount/ietf-netconf-monitoring:get-schema"
 local HTTP_BODY=""
 local HTTP_METHOD="POST"
 local HTTP_CONTENT_TYPE="application/xml"
 local HTTP_ACCEPT="application/xml"
 mk_tmp_file HTTP_RESPONSE
 mk_tmp_file HTTP_BODY
 echo "<input xmlns=\"urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring\">
  <identifier>${IDENTIFIER}</identifier>" > ${HTTP_BODY}
  echo "  <identifier>${IDENTIFIER,,}</identifier>" >> ${HTTP_BODY}
  [[ -n "${REVISION}" ]] && echo "  <revision>${REVISION}</revision>" >> ${HTTP_BODY} 
  echo "</input>" >> ${HTTP_BODY}
  http_curl "${HTTP_RESPONSE}" "${HTTP_METHOD}" "${HTTP_PATH}" "${HTTP_BODY}" "${HTTP_CONTENT_TYPE}" "${HTTP_ACCEPT}"
 if [ ${CURL_RETVAL} -eq 0 ] ; then
   if [ "${CURL_HTTP_CODE:0:1}" == "2" ] ; then
     local SCHEMAS=0
     SCHEMAS=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema | length" ${HTTP_RESPONSE})
     if [ ${SCHEMAS} -gt 0 ] ; then
       local SCHEMA=0
       echo "[]identifier|version|format|namespace|location"
       while [ ${SCHEMA} -lt ${SCHEMAS} ] ; do
         local IDENTIFIER=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].identifier" ${HTTP_RESPONSE})
         local VERSION=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].version" ${HTTP_RESPONSE})
         local FORMAT=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].format" ${HTTP_RESPONSE})
         local NAMESPACE=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].namespace" ${HTTP_RESPONSE})
         local LOCATION=$(jq -r ".\"ietf-netconf:output\".data.\"netconf-state\".schemas.schema[${SCHEMA}].location" ${HTTP_RESPONSE})
         echo "${IDENTIFIER}|${VERSION,,}|${FORMAT,,}|${NAMESPACE,,}|${LOCATION}"
         ((SCHEMA=SCHEMA+1))
       done
     fi
      RETVAL=0
   else
      RETVAL=${CURL_HTTP_CODE}
   fi
 fi
 rm_tmp_file "${HTTP_BODY}"
 rm_tmp_file "${HTTP_RESPONSE}"
 }

node_schema() {
  local RETVAL=0
  case "${1,,}" in
    help|?)
      yang_help_list
      RETVAL=0
      ;;
    list)
      shift
      node_schemas_list ${@}
      RETVAL=$?
      ;;
    fetch)
      shift
      node_schema_fetch ${@}
      RETVAL=$?
      ;;
    *)
      yang_help_list
      RETVAL=1
      ;;
  esac
  return ${RETVAL}
}

if [ $# -eq 0 ] ; then
  yang_help_list
  RETVAL=0
else
 case "${1,,}" in
  help|?)
    yang_help_list
    RETVAL=0
    ;;
  list)
    shift
    yang_list ${@}
    RETVAL=$?
    ;;
  node)
    shift
    node_schema ${@}
    RETVAL=$?
    ;;
  *)
    yang_help_list
    RETVAL=1
    ;;
 esac
fi
return ${RETVAL}


